name: audify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  flutter_downloader: ^1.7.0
  permission_handler: ^11.4.0 
  mime: ^2.0.0

  cupertino_icons: ^1.0.8
  file_picker: ^9.0.2
  http: ^0.13.5
  http_parser: ^4.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  audioplayers: ^6.4.0
  flutter_downloader: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/audify_logo.png
    - assets/images/upload icon.png
    - assets/images/green_tick.png
    - assets/images/audio_icon.png
    - assets/images/file_upload_success.png
    - assets/images/audio_convert.png
    - assets/images/device.png
